package demo.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EnumClass implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public EnumClass() {
    }

}