package demo.project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TestObjectData implements java.io.Serializable {

    static final long serialVersionUID = 1L;


    public TestObjectData() {
       public enum Color {
       RED, GREEN, ANY;
     };

     private Color color;    

     public Color getColor(){
        return color; 
     }

     public void setColor(Color color){
         this.color = color;
     }  
    }

}